### ISSUE TITLE
Update TrainNets and StaNNet

### ISSUE THREAD

**Issue by Mark-Boon** [WilliamElferink/SkyNEt#14]
The following additions to TrainNets and StaNNet should be added to the next update of those scripts:

- Functionality of training a pre-existing net. At the moment only when a NN is initialized it is possible to train it.
- Add a function that can generate input data. For the wave search experiment the input data can become quite large (in the order of gigabytes) and it is therefore more efficient to generate the input data corresponding to the output per minibatch.

**Comment by internetvandingen** [comment]
Addition feature request:
- consistency between 'input' and 'control' voltage representation, either all inputs of the network have actual voltage values or all inputs have a value in [0, 1].

**Comment by internetvandingen** [comment]
It has been decided that we are using actual voltages to train the model, so the model needs to be provided with actual voltages.
Information about voltage ranges and other things should be stored in the staNNet objects 'info' attribute.

**Comment by hcruiz** [comment]
> The following additions to TrainNets and StaNNet should be added to the next update of those scripts:
> 
> * Functionality of training a pre-existing net. At the moment only when a NN is initialized it is possible to train it.
> * Add a function that can generate input data. For the wave search experiment the input data can become quite large (in the order of gigabytes) and it is therefore more efficient to generate the input data corresponding to the output per minibatch.

@Mark-Boon Have you worked on any of these points?
I will update also the DataHandler to be compatible with at least your data format (sine sampling where you do not save the inputs but instead you generate them). Preparing the data will only assume that there are outputs, and if there are no inputs, it will generate them with sine waves. Do you have a function for this that I could import in the DataHandler?

**Comment by hcruiz** [comment]
@Mark-Boon @internetvandingen I think all suggestions are included. Let me know if you find any problems. 
@Mark-Boon Have you included the changes to combine staNNet and your light version? Let me know so I can close this.
