### ISSUE TITLE
conversion factor redundant in new NN update merge

### ISSUE THREAD

**Issue by hcruiz** [WilliamElferink/SkyNEt#25]
I leave it open to discuss the conversion factor

_Originally posted by @hcruiz in https://github.com/BraiNEdarwin/SkyNEt/pull/22#issuecomment-498262969_

**Comment by internetvandingen** [comment]
Additionally, it is not compatible with older networks and I think they should be for now.
Solution is to add the following code in stannet on line 97:
if 'conversion' not in self.info.keys():
    self.info['conversion'] = 1.0
