### ISSUE TITLE
Create config class

### ISSUE THREAD

**Issue by brambozz** [WilliamElferink/SkyNEt#3]
Create a config template class and a sub-config class that inherits from the template config class.

**Comment by hcruiz** [comment]
I have written two classes, the config_class and the experiment_config. The former is the parent of the latter.  The second class serves as a template for new users. I included to do's and comments. One convention I took is to give parameters names with small letters and methods names with capital letters. This makes it easier to differentiate them in the attribute list, so it is cleaner. This convention has to be carried out over all modules and I didn't implement it in the classes I wrote (is as a to do).
The next step is connecting this to the GA and the measurement script.
I tested that the object is correctly built and the inheritance works.
Let me know your thoughts and feel free to add comments and explanations there.

**Comment by hcruiz** [comment]
It is in de config_class branch and in the dev_v1 directory

**Comment by brambozz** [comment]
It looks very nice! I like the convention of separating methods and parameters. At this point I see no issues, I suppose some things will turn up when we start connecting to GA and measurement. 

One small question I have is using #%% to define sections in code. In Spyder this creates a block with a nice line, and I guess this convention was taken from Matlab? Will we stick to this, other editors (e.g. Sublime text, Atom) do not recognize this as such.

**Comment by hcruiz** [comment]
Hey. For the spyder users is a nice and useful separator but if I'm the only one using it and there are problems for leaving it there, then we might take it out. Otherwise I think it is nice to separate in logical blocks

**Comment by brambozz** [comment]
I like to use spyder as well, so I suggest we leave it then. Or even make it a convention in all other files as well.
