### ISSUE TITLE
Install SkyNEt as a module

### ISSUE THREAD

**Issue by brambozz** [WilliamElferink/SkyNEt#4]
We need to look at the installation instruction again. We don't install SkyNEt as a module, but it would be better if we did. That way we can access it in any script (also in subdirectories). These instructions have to be included in the readme.

**Comment by brambozz** [comment]
I have updated the installation procedure and this should now circumvent this problem, perhaps someone can check this.

**Comment by brambozz** [comment]
Installation instructions seem fine, but perhaps this is not the best way to fix it. We could someday look into this. Leaving the issue open for now, without any work on it expected soon.

**Comment by hcruiz** [comment]
The path to SkyNEt is added to the Python path
