### ISSUE TITLE
Bug while loading net in sys without cuda

### ISSUE THREAD

**Issue by hcruiz** [WilliamElferink/SkyNEt#5]
The code breaks whenever a user loads a net saved with torch.cuda.FloatTensor type AND the system has no cuda.
The line is in the _load_model method of staNNet: 
In line: 
if isinstance(layers[-1][1],torch.cuda.FloatTensor): ...

layers[-1][1] is a torch.Tensor from the loaded model with torch.load with appropiate kwarg to load to cpu. If other dtypes are used in isinstance it works.

**Comment by internetvandingen** [comment]
This got fixed with #11 merge.
