### ISSUE TITLE
saveExperiment copyfile from other working directory

### ISSUE THREAD

**Issue by brambozz** [WilliamElferink/SkyNEt#7]

**Comment by brambozz** [comment]
Probably best way is:
- get filepath of experiment config inside experiment config
- pass it along to saveExperiment

**Comment by hcruiz** [comment]
Is this closed? What is the status of this and what actions do we need to take to avoid conflicts/breaking the code?

**Comment by hcruiz** [comment]
If we use sys.argv[0], we can get the path of the file that we run and save the files used with saveExperiment. We don't need to pas it along to saveExperiment. A small example that saves the file that you run:

import shutil
import time
import sys

def egosave(dst):
    f = sys.argv[0].split('/')[-1]
    f = f.strip('.py')
    new_file = f+'-'+time.strftime('%Y_%m_%d')+'.py'
    dst += '/'+new_file
    print('Using sys.argv[0] as source file: ',sys.argv[0])
    print('I saved myself in ',dst)
    shutil.copy(sys.argv[0],dst)

**Comment by hcruiz** [comment]
If we use sys.argv[0], we can get the path of the file that we run and save the files used with saveExperiment. We don't need to pas it along to saveExperiment. A small example that saves the file that you run:
```
import shutil
import time
import sys

def egosave(dst):
    f = sys.argv[0].split('/')[-1]
    f = f.strip('.py')
    new_file = f+'-'+time.strftime('%Y_%m_%d')+'.py'
    dst += '/'+new_file
    print('Using sys.argv[0] as source file: ',sys.argv[0])
    print('I saved myself in ',dst)
    shutil.copy(sys.argv[0],dst)
```
