### ISSUE TITLE
evolution should not require nidaqmx

### ISSUE THREAD

**Issue by internetvandingen** [WilliamElferink/SkyNEt#9]
Evolution requires an object of the config class, which in turn requires nidaqmx.
In my opinion this is something related to measuring an experiment/measuring and not to the evolution itself.
I do not have the complete picture here because it states: # Import needed for reset handling,

**Comment by brambozz** [comment]
I agree, I think that the imports should not be necessary looking at it again. I will do some tests when nobody is measuring next week. For now I think you can comment it out on your branch, should not give errors I think.

**Comment by hcruiz** [comment]
Shouldn't reset() be a method of instruments or nidaq and adwin?

**Comment by brambozz** [comment]
That could also be a way of handling. The reasoning behind putting it in the config class was that this way it is always included in any experiment. Resetting the measurement equipment is important enough for that imo. But let's see if we can circumvent the imports, then it is no problem anyways.

**Comment by internetvandingen** [comment]
Thanks for the response!
